# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d8ca3a1314c924fc9c804b16e78c450c4936472bdd1eff6cc6fe2837674608b5b47fd1052f29c5d6c18773016fc7fad1ae25a74f66352363618b7b0b3eaa84a

test:
  secret_key_base: 8058757d6bd5e84c121bfd1546ddf56806bedc37e7ebdb2f8a45ef016e82048fdbc5bd019ec2bd7111cf5d350d151650ac19a3afb0bf91f1b23491dbdc01769f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
